import { Plugin } from 'vite'
import fs from 'node:fs/promises'
import path from 'node:path'
import glob from 'fast-glob'

export default function iconTypesPlugin(): Plugin {
    const SVG_DIR = 'src/assets/svg'
    const TYPE_FILE = 'src/types/icon.d.ts'

    async function generateTypes() {
        const svgFiles = await glob('*.svg', {
            cwd: SVG_DIR,
            absolute: false,
        })

        const iconNames = svgFiles.map((file) => path.basename(file, '.svg'))

        const content = `// Generated by vite-plugin-icon-types
declare type IconName = ${iconNames.map((name) => `'${name}'`).join(' | ')}
`

        await fs.mkdir(path.dirname(TYPE_FILE), { recursive: true })
        await fs.writeFile(TYPE_FILE, content, 'utf-8')
    }

    return {
        name: 'vite-plugin-icon-types',

        async buildStart() {
            await generateTypes()
        },

        configureServer(server) {
            server.watcher.add(SVG_DIR)
            server.watcher.on('add', async (file) => {
                if (file.includes(SVG_DIR) && file.endsWith('.svg')) {
                    await generateTypes()
                }
            })
            server.watcher.on('unlink', async (file) => {
                if (file.includes(SVG_DIR) && file.endsWith('.svg')) {
                    await generateTypes()
                }
            })
        },
    }
}
